# Generated by Django 2.1.2 on 2020-09-29 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nm_curso', models.CharField(max_length=50, unique=True, verbose_name='Nome do Curso')),
                ('sigla_curso', models.CharField(max_length=5, unique=True, verbose_name='Sigla do Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('ds_disciplina', models.CharField(max_length=50, verbose_name='Descrição da Disciplina')),
                ('sigla_disciplina', models.CharField(max_length=5, unique=True, verbose_name='Sigla da Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id_gene', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False)),
                ('cd_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Gene', verbose_name='Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('1', 'Domingo-Feira'), ('2', 'Segunda-Feira'), ('3', 'Terça-Feira'), ('4', 'Quarta-Feira'), ('5', 'Quinta-Feira'), ('6', 'Sexta-Feira'), ('7', 'Sábado')], max_length=20, verbose_name='Dia da semana')),
                ('horario', models.IntegerField(choices=[(1, '19:20 às 20:50'), (2, '21:10 às 22:50'), (3, '08:20 às 10:50'), (4, '11:10 às 12:40')], verbose_name='Horario')),
                ('turno', models.CharField(choices=[('1', 'Matutino'), ('2', 'Vespertino'), ('3', 'Noturno')], max_length=20, verbose_name='Turno')),
            ],
            options={
                'verbose_name_plural': 'Horários',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Disciplina', verbose_name='Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nm_professor', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('ds_sala', models.CharField(max_length=20, unique=True, verbose_name='Sala')),
                ('andar', models.CharField(max_length=2, verbose_name='Andar')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('ds_turma', models.CharField(max_length=20, unique=True, verbose_name='Descrição da Turma')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Turma', verbose_name='Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('dia_semana', 'horario', 'turno')},
        ),
        migrations.AddField(
            model_name='grade',
            name='cd_oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Oferta', verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='gene',
            name='cd_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Horario', verbose_name='cd_horario'),
        ),
        migrations.AddField(
            model_name='gene',
            name='cd_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Professor', verbose_name='cd_professor'),
        ),
        migrations.AddField(
            model_name='gene',
            name='cd_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Sala', verbose_name='cd_sala'),
        ),
        migrations.AlterUniqueTogether(
            name='professor',
            unique_together={('matricula',)},
        ),
        migrations.AlterUniqueTogether(
            name='oferta',
            unique_together={('curso', 'turma', 'disciplina')},
        ),
    ]
