# Generated by Django 2.1.2 on 2020-09-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='semestre',
            field=models.CharField(choices=[(1, '1º Semestre'), (2, '2º Semestre'), (3, '3º Semestre'), (4, '4º Semestre'), (5, '5º Semestre'), (6, '6º Semestre'), (7, '7º Semestre'), (8, '8º Semestre'), (9, '9º Semestre'), (10, '10ºSemestre')], default=1, max_length=20, verbose_name='Semestre'),
            preserve_default=False,
        ),
    ]
