# Generated by Django 2.1.2 on 2020-10-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0003_auto_20200928_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
    ]
