# Generated by Django 2.1.2 on 2020-10-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0004_remove_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='ds_turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='cd_turma',
            field=models.IntegerField(default=1111, unique=True, verbose_name='Descrição da Turma'),
            preserve_default=False,
        ),
    ]
