# Generated by Django 2.1.2 on 2020-10-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0005_auto_20201006_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='cd_turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='ds_turma',
            field=models.CharField(default=11, max_length=20, unique=True, verbose_name='Descrição da Turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre'), (3, '3º Semestre'), (4, '4º Semestre'), (5, '5º Semestre'), (6, '6º Semestre'), (7, '7º Semestre'), (8, '8º Semestre'), (9, '9º Semestre'), (10, '10ºSemestre')], verbose_name='Semestre'),
        ),
    ]
