# Generated by Django 2.1.2 on 2020-10-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0006_auto_20201006_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='cd_oferta',
        ),
        migrations.AddField(
            model_name='gene',
            name='gene',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Oferta', verbose_name='cd_gene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinas',
            field=models.ManyToManyField(related_name='professor_disciplina', to='gradehoraria.Disciplina', verbose_name='Disciplina'),
        ),
    ]
