# Generated by Django 2.1.2 on 2020-10-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0007_auto_20201014_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosGrade',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('tamanhoPopulacao', models.IntegerField(verbose_name='População Inicial')),
                ('numeroGeracoes', models.IntegerField(verbose_name='Qtd. máxima de tentativas')),
                ('taxaMutacao', models.IntegerField(verbose_name='Taxa de Mutação')),
            ],
        ),
        migrations.RenameField(
            model_name='gene',
            old_name='gene',
            new_name='oferta',
        ),
    ]
