# Generated by Django 2.1.2 on 2020-10-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0009_auto_20201015_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Domingo-Feira'), (2, 'Segunda-Feira'), (3, 'Terça-Feira'), (4, 'Quarta-Feira'), (5, 'Quinta-Feira'), (6, 'Sexta-Feira'), (7, 'Sábado')], max_length=20, verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')], max_length=20, verbose_name='Turno'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('dia_semana', 'turno', 'horario')},
        ),
    ]
