# Generated by Django 2.1.2 on 2020-10-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0012_auto_20201018_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.IntegerField(choices=[(1, '08:20 às 10:50'), (2, '11:10 às 12:40'), (3, '19:20 às 20:50'), (4, '21:10 às 22:50')], verbose_name='Horario'),
        ),
    ]
