# Generated by Django 2.1.2 on 2020-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0013_auto_20201018_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Matutino'), (2, 'Noturno')], verbose_name='Turno'),
        ),
    ]
