# Generated by Django 2.1.2 on 2020-10-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0014_auto_20201018_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosgrade',
            name='paramTurma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Turma', verbose_name='cd_turma'),
            preserve_default=False,
        ),
    ]
