# Generated by Django 2.1.2 on 2020-10-27 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0015_parametrosgrade_paramturma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosgrade',
            name='paramTurma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Turma', verbose_name='Turma'),
        ),
    ]
