# Generated by Django 2.1.2 on 2020-10-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0016_auto_20201026_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')], verbose_name='Turno'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='horario',
        ),
    ]
