# Generated by Django 2.1.2 on 2020-10-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0016_auto_20201026_2124'),
    ]

    operations = [

    ]
