# Generated by Django 2.1.2 on 2020-10-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0017_auto_20201030_2126'),
    ]

    operations = [

    ]
