# Generated by Django 2.1.2 on 2020-10-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0017_auto_20201030_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')], default=5, verbose_name='Turno'),
            preserve_default=False,
        ),
    ]
