# Generated by Django 2.1.2 on 2020-11-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0018_auto_20201030_2352'),
    ]

    operations = [

        migrations.AlterUniqueTogether(
            name='gene',
            unique_together={('id_gene', 'cd_professor', 'cd_horario', 'cd_sala', 'oferta')},
        ),

    ]
