# Generated by Django 2.1.2 on 2020-11-12 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0019_auto_20201111_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={},
        ),
        migrations.RenameField(
            model_name='gene',
            old_name='id_gene',
            new_name='gene_id',
        ),
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')], default=1, verbose_name='Turno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='cd_gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Gene', to_field='id_gene', verbose_name='Gene'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.IntegerField(choices=[(1, '1 - Horário'), (2, '2 - Horário'), (3, '3 - Horário'), (4, '4 - Horário'), (5, '5 - Horário'), (6, '6 - Horário')], verbose_name='Horário'),
        ),
        migrations.AlterUniqueTogether(
            name='gene',
            unique_together={('gene_id', 'cd_professor', 'cd_horario', 'cd_sala', 'oferta')},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='turno',
        ),
    ]
