# Generated by Django 2.1.2 on 2020-11-12 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0020_auto_20201111_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='oferta',
            new_name='cd_oferta',
        ),
        migrations.AddField(
            model_name='gene',
            name='cd_gene',
            field=models.IntegerField(default=0, verbose_name='Gene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='cd_gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Gene', verbose_name='Gene'),
        ),
        migrations.RemoveField(
            model_name='gene',
            name='gene_id',
        ),
        migrations.AlterUniqueTogether(
            name='gene',
            unique_together={('cd_gene', 'cd_professor', 'cd_horario', 'cd_sala', 'cd_oferta')},
        ),
    ]
