# Generated by Django 2.1.2 on 2020-11-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0021_auto_20201112_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='cd_oferta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Oferta', verbose_name='cd_oferta'),
        ),
    ]
