# Generated by Django 2.1.2 on 2020-11-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0022_auto_20201114_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='cd_turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Turma', verbose_name='Turma'),
            preserve_default=False,
        ),
    ]
