# Generated by Django 2.1.2 on 2020-11-14 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0023_auto_20201114_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='cd_gene',
        ),
        migrations.AddField(
            model_name='gene',
            name='cd_turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Turma', verbose_name='Turma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='gene_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gene',
            name='cd_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Horario', verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='cd_oferta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Oferta', verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='cd_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Professor', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='cd_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Sala', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.IntegerField(choices=[(1, '1 - Horário'), (2, '2 - Horário'), (3, '3 - Horário'), (4, '4 - Horário'), (5, '5 - Horário'), (6, '6 - Horário'), (7, '7 - Horário'), (8, '8 - Horário'), (9, '9 - Horário'), (10, '10 - Horário'), (11, '11 - Horário'), (12, '12 - Horário')], verbose_name='Horário'),
        ),
        migrations.RemoveField(
            model_name='gene',
            name='cd_gene',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='gene',
            unique_together={('cd_turma', 'cd_professor', 'cd_horario', 'cd_sala', 'cd_oferta')},
        ),
    ]
