# Generated by Django 2.1.2 on 2020-11-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0024_auto_20201114_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='cd_geracao',
            field=models.IntegerField(default=100, verbose_name='Geração'),
            preserve_default=False,
        ),
    ]
