# Generated by Django 2.1.2 on 2020-11-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0025_gene_cd_geracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='cd_geracao',
        ),
        migrations.AddField(
            model_name='grade',
            name='cd_geracao',
            field=models.IntegerField(default=0, verbose_name='Geração'),
            preserve_default=False,
        ),
    ]
