# Generated by Django 2.1.2 on 2020-11-15 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0026_auto_20201114_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='cd_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gradehoraria.Curso', verbose_name='Curso'),
            preserve_default=False,
        ),
    ]
