# Generated by Django 2.1.2 on 2020-11-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradehoraria', '0028_auto_20201115_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='resultado',
        ),
    ]
